FROM apache/airflow:3.2.0-python3.12
USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/airflow/home /opt/airflow/src /opt/airflow/dags && \
    chown -R airflow:root /opt/airflow
USER airflow

WORKDIR /opt/airflow

COPY pyproject.toml .

RUN pip install --no-cache-dir --user .

ENV AIRFLOW_HOME=/opt/airflow/home
ENV PYTHONPATH=/opt/airflow